routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin Routes
Route::patch('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status');
Route::get('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status.get');


Route::prefix(config('app.admin_path'))->name('admin.')->namespace('Admin')->group(function () {
	Route::get('/', function () {
		return redirect()->route('admin.home');
	});

	Route::get('login', 'AuthController@index')->name('login');
	Route::post('login', 'AuthController@login')->name('login');
	Route::post('logout', 'AuthController@logout')->name('logout');

	Route::prefix('form-surat')->group(function () {
		Route::get('/', 'FormSuratController@index')->name('formsurat');
		Route::post('store/{letter}', 'FormSuratController@store')->name('formsurat.store');
	});

	Route::prefix('pencatatan')->group(function () {
		Route::get('/', 'PencatatanSuratController@index')->name('pencatatan');
		Route::post('store', 'PencatatanSuratController@store')->name('pencatatan.store');
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::post('cetaks', 'LaporanController@cetakPemerintahan')->name('laporan.cetak.kpemerintahan');
		Route::post('cetak/masuk', 'LaporanController@cetakMasuk')->name('laporan.cetak.masuk');

		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});

	Route::middleware('auth:admin')->group(function () {
		Route::get('home', 'HomeController@index')->name('home');

		Route::prefix('submissions')->name('submissions.')->group(function () {
			Route::get('pending', 'SubmissionController@pending')->name('pending');
			Route::get('approved', 'SubmissionController@approved')->name('approved');
			Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
			Route::post('approved/export', 'SubmissionController@exportApproved')->name('approved.export');
			Route::get('rejected', 'SubmissionController@rejected')->name('rejected');
			Route::get('show/{id}', 'SubmissionController@show')->name('show');

			Route::patch('update/{id}', 'SubmissionController@update')->name('update');
			Route::post('print/{id}', 'SubmissionController@print')->name('print');
		});

		Route::resource('data', 'AdminController');
		Route::resource('users', 'UserController');
		Route::resource('letters', 'LetterController');
		Route::resource('signatories', 'SignatoryController');
		Route::view('helpers', 'admin.helper.index')->name('helpers');

		Route::prefix('user')->group(function () {
			Route::get('approval/{status}/{id}', 'UserController@approval')->name('user.approval');
		});

		Route::prefix('import')->name('import.')->group(function () {
			Route::post('data', 'ImportController@admin')->name('data');
			Route::post('users', 'ImportController@user')->name('users');
		});

		Route::prefix('account')->group(function () {
			Route::get('/', 'AccountController@index')->name('account');
			Route::patch('/', 'AccountController@update')->name('account');
			Route::name('account.')->group(function () {
				Route::get('password', 'AccountController@password')->name('password');
				Route::patch('password', 'AccountController@patchPassword')->name('password');
				Route::get('logs', 'AccountController@logs')->name('logs');
			});
		});

		Route::prefix('settings')->name('settings')->group(function () {
			Route::get('/', 'SettingController@index');
			Route::patch('/', 'SettingController@update');
		});

		Route::prefix('datatables')->name('datatables.')->group(function () {
			Route::post('users', 'DataController@users')->name('users');
			Route::post('submissions/pending', 'DataController@submissionsPending')->name('submissions.pending');
			Route::post('submissions/approved', 'DataController@submissionsApproved')->name('submissions.approved');
			Route::post('submissions/rejected', 'DataController@submissionsRejected')->name('submissions.rejected');
			Route::post('submissions/selesai', 'DataController@submissionSelesai')->name('submissions.selesai');
		});
	});
});

// User Routes
Route::get('/', 'HomeController@index2');

Route::get('login', 'AuthController@index')->name('login');
Route::get('registrasi', 'AuthController@registrasi')->name('registrasi');
Route::post('registrasi', 'AuthController@registrasiStore')->name('registrasi.store');
Route::post('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@login')->name('login');
Route::post('lupa-password', 'AuthController@lupaPassword')->name('lupa');
Route::post('lupa-password-proses/{id}', 'AuthController@lupaPasswordProses')->name('lupa.proses');
Route::get('reset-password/{token}', 'AuthController@resetPassword')->name('reset.password');
Route::post('logout', 'AuthController@logout')->name('logout');

Route::middleware('auth')->group(function () {
	Route::get('home', 'HomeController@index')->name('home');
	Route::get('submissions', 'SubmissionController@index')->name('submissions.index');
	Route::get('submissions/add', 'SubmissionController@add')->name('submissions.add');
	Route::post('submissions/store/{letter}', 'SubmissionController@store')->name('submissions.store');

	Route::prefix('account')->group(function () {
		Route::get('/', 'AccountController@index')->name('account');
		Route::get('/edit', 'AccountController@indexEdit')->name('account.edit');
		Route::post('/update', 'AccountController@update')->name('account.update');
		Route::name('account.')->group(function () {
			Route::post('whatsapp', 'AccountController@whatsapp')->name('whatsapp');
			Route::get('password', 'AccountController@password')->name('password');
			Route::patch('password', 'AccountController@patchPassword')->name('password');
			Route::get('logs', 'AccountController@logs')->name('logs');
		});
	});

	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});
	Route::prefix('submissions')->name('submissions.')->group(function () {
		Route::get('pending', 'SubmissionController@pending')->name('pending');
		Route::get('approved', 'SubmissionController@approved')->name('approved');
		Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
		Route::post('print/{id}', 'Admin\SubmissionController@print')->name('print');
		Route::get('show/{id}', 'SubmissionController@show')->name('show');
	});
});

app/Http/Controllers/Admin/DataController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Submission;
use App\User;

class DataController extends Controller
{
    public function users()
    {
        return datatables()->of(User::all())->toJson();
    }

    public function submissionsPending()
    {
        $submissions = Submission::with('user', 'letter')
        ->where('approval_status', 0)
        ->get();

        return datatables()->of($submissions)->toJson();
    }

    public function submissionsApproved()
    {
        $submissions = Submission::with('user', 'letter')
        ->where('approval_status', 1)
        ->get();

        return datatables()->of($submissions)->toJson();
    }

    public function submissionsRejectedPending()
    {
        $submissions = Submission::with('user', 'letter')
        ->where('approval_status', 2)
        ->get();

        return datatables()->of($submissions)->toJson();
    }
}

resources/views/admin/data/create.blade.php
@extends('admin.layouts.master')

@section('title', 'Tambah Data Admin')

@section('content')

<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        @component('admin.components.breadcumb')
        @slot('title') Tambah Data Admin @endslot
        @slot('li_1') Admin @endslot
        @endcomponent
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Tambah Data Admin</h4>
                <p class="card-title-desc">Silahkan isi dengan benar form dibawah.</p>

                @include('admin.components.message')

                <form class="custom-validation" method="POST" action="{{ route('admin.data.store') }}"
                    enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="photo" class="col-sm-2 col-form-label">Foto</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="file" name="photo" id="photo">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Nama *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}"
                                data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="username" class="col-sm-2 col-form-label">Username *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="username" id="username"
                                value="{{ old('name') }}" data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="username" class="col-sm-2 col-form-label">Email *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="email" id="email"
                                value="{{ old('email') }}" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="position" class="col-sm-2 col-form-label">Status *</label>
                        <div class="col-sm-10">
                           <select name="status" required class="form-control" id="">
                                <option value="">- Pilih Status -</option>
                                <option value="1">Aktif</option>
                                <option value="0">Tidak Aktif</option>
                           </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-sm-2 col-form-label">Password *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="password" name="password" id="password"
                                data-parsley-length="[6,255]" required>
                        </div>
                    </div>
                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary waves-effect waves-light mr-1">
                                Submit
                            </button>
                            <a class="btn btn-secondary waves-effect waves-light"
                                href="{{ route('admin.users.index') }}" role="button">Cancel</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@endsection

@section('script')
<!-- Plugins js -->
<script src="{{ URL::asset('assets/libs/parsleyjs/parsleyjs.min.js') }}"></script>

<script src="{{ URL::asset('assets/js/pages/form-validation.init.js') }}"></script>
@endsection

resources/views/admin/data/edit.blade.php
@extends('admin.layouts.master')

@section('title', 'Edit Data Admin: '. $admin->name)

@section('css')
<link href="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        @component('admin.components.breadcumb')
        @slot('title') Edit Data Admin: {{ $admin->name }} @endslot
        @slot('li_1') Admin @endslot
        @endcomponent
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Edit Data Admin: {{ $admin->name }}</h4>
                <p class="card-title-desc">Silahkan edit dengan benar form dibawah.</p>

                @include('admin.components.message')

                <form class="custom-validation" method="POST" action="{{ route('admin.data.update', $admin->id) }}"
                    enctype="multipart/form-data">
                    @csrf
                    @method('PATCH')
                    <div class="form-group row">

                        <label for="photo" class="col-sm-2 col-form-label">Foto</label>
                        <div class="col-sm-10">
                            <a class="image-popup-no-margins" href="{{ asset($admin->photo) }}">
                                <img class="img-fluid" alt="{{ $admin->name }}" src="{{ asset($admin->photo) }}"
                                    width="120">
                            </a>
                            <input class="form-control mt-2" type="file" name="photo" id="photo">
                            <p class='help-block'>Please leave empty if not change.</p>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Nama *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="name" id="name"
                                value="{{ old('name') ?? $admin->name }}" data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="username" class="col-sm-2 col-form-label">Username *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="username" id="username"
                                value="{{ old('name') ?? $admin->username }}" data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="username" class="col-sm-2 col-form-label">Email *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="email" id="email"
                                value="{{ old('name') ?? $admin->email}}" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="position" class="col-sm-2 col-form-label">Status *</label>
                        <div class="col-sm-10">
                           <select name="status" required class="form-control" id="">
                                <option value="">- Pilih Status -</option>
                                <option value="1" {{ $admin->is_active == 1 ? 'selected'  : ''}}>Aktif</option>
                                <option value="0" {{ $admin->is_active == 0 ? 'selected' : ''}}>Tidak Aktif</option>
                           </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-sm-2 col-form-label">Password *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="password" name="password" id="password"
                                data-parsley-length="[6,255]">
                            <p class='help-block'>Please leave empty if not change.</p>
                        </div>
                    </div>
                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary waves-effect waves-light mr-1">
                                Submit
                            </button>
                            <a class="btn btn-secondary waves-effect waves-light" href="{{ route('admin.data.index') }}"
                                role="button">Cancel</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@endsection

@section('script')
<!-- Plugins js -->
<script src="{{ URL::asset('assets/libs/parsleyjs/parsleyjs.min.js')}}"></script>
<script src="{{ URL::asset('assets/js/pages/form-validation.init.js')}}"></script>
<script src="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.js')}}"></script>

<script src="{{ URL::asset('assets/js/pages/lightbox.init.js')}}"></script>
@endsection

resources/views/admin/data/index.blade.php
@extends('admin.layouts.master')

@section('title', 'Data Admin')

@section('css')
<link href="{{ URL::asset('assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        @component('admin.components.breadcumb')
        @slot('title') Data Admin @endslot
        @slot('li_1') Admin @endslot
        @endcomponent
    </div>

    <div class="col-sm-6">
        <div class="float-right d-md-block mb-3">
            <div class="dropdown">
                <a href="{{ route('admin.data.create') }}" class="btn btn-primary waves-effect waves-light">
                    <i class="mdi mdi-gesture-spread mr-2"></i> Tambah Data
                </a>
        
                <div class="modal fade import-modal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel"
                    aria-hidden="true">
                    <div class="modal-dialog modal-dialog-centered">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title mt-0">Import Data Admin</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                            </div>
                            <div class="modal-body">
                                <form class="custom-validation" method="POST" action="{{ route('admin.import.data') }}"
                                    enctype="multipart/form-data">
                                    @csrf
                                    <div class="form-group row">
                                        <label for="file_import" class="col-sm-2 col-form-label">File</label>
                                        <div class="col-sm-10">
                                            <input class="form-control" type="file" name="file_import" id="file_import"
                                                accept=".csv, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel">
                                            <p class='help-block'>Silahkan Download File Samplenya <a
                                                    href="{{ asset('import/admin.xlsx') }}">Disini</a>.</p>
                                        </div>
                                    </div>
                                    <div class="form-group mb-0">
                                        <div>
                                            <button type="submit" class="btn btn-primary waves-effect waves-light mr-1">
                                                Submit
                                            </button>
                                            <a class="btn btn-secondary waves-effect waves-light" role="button"
                                                data-dismiss="modal" aria-hidden="true">Cancel</a>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div><!-- /.modal-content -->
                    </div><!-- /.modal-dialog -->
                </div><!-- /.modal -->
            </div>
        </div>
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Data Admin</h4>
                @include('admin.components.message')
                <table id="datatable" class="table table-bordered dt-responsive nowrap"
                    style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>Foto</th>
                            <th>Nama</th>
                            <th>Username</th>
                            <th>Email</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($admins as $admin)
                        <tr>
                            <td>
                                <a class="image-popup-no-margins" href="{{ asset($admin->photo) }}">
                                    <img class="img-fluid" alt="{{ $admin->name }}" src="{{ asset($admin->photo) }}"
                                        width="24">
                                </a>
                            </td>
                            <td>{{ $admin->name }}</td>
                            <td>{{ $admin->username }}</td>
                            <td>{{ $admin->email }}</td>
                            <td>{{ $admin->is_active == 1 ? 'Aktif' : 'Tidak Aktif' }}</td>
                            <td>
                                <a class="btn btn-sm btn-warning waves-effect waves-light"
                                    href="{{ route('admin.data.edit', $admin->id) }}" role="button"><i
                                        class="mdi mdi-grease-pencil"></i></a>
                                <form method="POST" action="{{ route('admin.data.destroy', $admin->id) }}"
                                    class="d-inline form-delete">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger waves-effect waves-light"><i
                                            class="mdi mdi-trash-can"></i></button>
                                </form>
                                <a class="btn btn-sm btn-info waves-effect waves-light"
                                    href="{{ route('admin.data.show', $admin->id) }}" role="button"><i
                                        class="mdi mdi mdi-eye-circle"></i></a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@endsection

@section('script')

<!-- Plugins js -->
<script src="{{ URL::asset('assets/libs/datatables/datatables.min.js')}}"></script>
<script src="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.js')}}"></script>
<script src="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.js')}}"></script>

<script src="{{ URL::asset('assets/js/pages/datatables.init.js')}}"></script>
<script src="{{ URL::asset('assets/js/pages/lightbox.init.js')}}"></script>

<script type="text/javascript">
    $(document).on('submit', '.form-delete', function (e) {
        var form = this;
        e.preventDefault();
        Swal.fire({
            title: "Are you sure?",
            text: "You won't be able to revert this!",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#34c38f",
            cancelButtonColor: "#f46a6a",
            confirmButtonText: "Yes, delete it!"
        }).then(function (result) {
            if (result.value) {
                return form.submit();
            }
        });
    });

</script>

@endsection

resources/views/admin/data/show.blade.php
@extends('admin.layouts.master')

@section('title', 'Detail Admin: ' . $admin->name)

@section('css')
<link href="{{ URL::asset('assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        @component('admin.components.breadcumb')
        @slot('title') Detail Admin: {{ $admin->name }} @endslot
        @slot('li_1') Admin @endslot
        @endcomponent
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table class='table table-bordered'>
                    <tbody>
                        <tr class='active'>
                            <td colspan="2"><strong><i class='fa fa-bars'></i> Detail Admin</strong></td>
                        </tr>
                        <tr>
                            <td width="25%"><strong>Photo</strong></td>
                            <td>
                                <a class="image-popup-no-margins" href="{{ asset($admin->photo) }}">
                                    <img class="img-fluid" alt="{{ $admin->name }}" src="{{ asset($admin->photo) }}"
                                        width="24">
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td><strong>Name</strong></td>
                            <td>{{ $admin->name }}</td>
                        </tr>
                        <tr>
                            <td><strong>Username</strong></td>
                            <td>{{ $admin->username }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Log Activity</h4>
                <table id="datatable" class="table table-bordered dt-responsive nowrap"
                    style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Page</th>
                            <th>Description</th>
                            <th>Method</th>
                            <th>URL</th>
                            <th>IP</th>
                            <th>Agent</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($logs as $log)
                        <tr>
                            <td>{{ $log->created_at->formatLocalized('%d %B %Y %H:%M') }}</td>
                            <td>{{ $log->page }}</td>
                            <td>{{ $log->description }}</td>
                            <td>{{ $log->method }}</td>
                            <td><a href="{{ $log->url }}" title="{{ $log->page }}">{{ $log->url }}</a></td>
                            <td>{{ $log->ip }}</td>
                            <td>{{ $log->agent }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@endsection

@section('script')

<!-- Plugins js -->
<script src="{{ URL::asset('assets/libs/datatables/datatables.min.js')}}"></script>
<script src="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.js')}}"></script>

<script src="{{ URL::asset('assets/js/pages/datatables.init.js')}}"></script>
<script src="{{ URL::asset('assets/js/pages/lightbox.init.js')}}"></script>

@endsection