routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin Routes
Route::patch('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status');
Route::get('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status.get');


Route::prefix(config('app.admin_path'))->name('admin.')->namespace('Admin')->group(function () {
	Route::get('/', function () {
		return redirect()->route('admin.home');
	});

	Route::get('login', 'AuthController@index')->name('login');
	Route::post('login', 'AuthController@login')->name('login');
	Route::post('logout', 'AuthController@logout')->name('logout');

	Route::prefix('form-surat')->group(function () {
		Route::get('/', 'FormSuratController@index')->name('formsurat');
		Route::post('store/{letter}', 'FormSuratController@store')->name('formsurat.store');
	});

	Route::prefix('pencatatan')->group(function () {
		Route::get('/', 'PencatatanSuratController@index')->name('pencatatan');
		Route::post('store', 'PencatatanSuratController@store')->name('pencatatan.store');
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::post('cetaks', 'LaporanController@cetakPemerintahan')->name('laporan.cetak.kpemerintahan');
		Route::post('cetak/masuk', 'LaporanController@cetakMasuk')->name('laporan.cetak.masuk');

		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});

	Route::middleware('auth:admin')->group(function () {
		Route::get('home', 'HomeController@index')->name('home');

		Route::prefix('submissions')->name('submissions.')->group(function () {
			Route::get('pending', 'SubmissionController@pending')->name('pending');
			Route::get('approved', 'SubmissionController@approved')->name('approved');
			Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
			Route::post('approved/export', 'SubmissionController@exportApproved')->name('approved.export');
			Route::get('rejected', 'SubmissionController@rejected')->name('rejected');
			Route::get('show/{id}', 'SubmissionController@show')->name('show');

			Route::patch('update/{id}', 'SubmissionController@update')->name('update');
			Route::post('print/{id}', 'SubmissionController@print')->name('print');
		});

		Route::resource('data', 'AdminController');
		Route::resource('users', 'UserController');
		Route::resource('letters', 'LetterController');
		Route::resource('signatories', 'SignatoryController');
		Route::view('helpers', 'admin.helper.index')->name('helpers');

		Route::prefix('user')->group(function () {
			Route::get('approval/{status}/{id}', 'UserController@approval')->name('user.approval');
		});

		Route::prefix('import')->name('import.')->group(function () {
			Route::post('data', 'ImportController@admin')->name('data');
			Route::post('users', 'ImportController@user')->name('users');
		});

		Route::prefix('account')->group(function () {
			Route::get('/', 'AccountController@index')->name('account');
			Route::patch('/', 'AccountController@update')->name('account');
			Route::name('account.')->group(function () {
				Route::get('password', 'AccountController@password')->name('password');
				Route::patch('password', 'AccountController@patchPassword')->name('password');
				Route::get('logs', 'AccountController@logs')->name('logs');
			});
		});

		Route::prefix('settings')->name('settings')->group(function () {
			Route::get('/', 'SettingController@index');
			Route::patch('/', 'SettingController@update');
		});

		Route::prefix('datatables')->name('datatables.')->group(function () {
			Route::post('users', 'DataController@users')->name('users');
			Route::post('submissions/pending', 'DataController@submissionsPending')->name('submissions.pending');
			Route::post('submissions/approved', 'DataController@submissionsApproved')->name('submissions.approved');
			Route::post('submissions/rejected', 'DataController@submissionsRejected')->name('submissions.rejected');
			Route::post('submissions/selesai', 'DataController@submissionSelesai')->name('submissions.selesai');
		});
	});
});

// User Routes
Route::get('/', 'HomeController@index2');

Route::get('login', 'AuthController@index')->name('login');
Route::get('registrasi', 'AuthController@registrasi')->name('registrasi');
Route::post('registrasi', 'AuthController@registrasiStore')->name('registrasi.store');
Route::post('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@login')->name('login');
Route::post('lupa-password', 'AuthController@lupaPassword')->name('lupa');
Route::post('lupa-password-proses/{id}', 'AuthController@lupaPasswordProses')->name('lupa.proses');
Route::get('reset-password/{token}', 'AuthController@resetPassword')->name('reset.password');
Route::post('logout', 'AuthController@logout')->name('logout');

Route::middleware('auth')->group(function () {
	Route::get('home', 'HomeController@index')->name('home');
	Route::get('submissions', 'SubmissionController@index')->name('submissions.index');
	Route::get('submissions/add', 'SubmissionController@add')->name('submissions.add');
	Route::post('submissions/store/{letter}', 'SubmissionController@store')->name('submissions.store');

	Route::prefix('account')->group(function () {
		Route::get('/', 'AccountController@index')->name('account');
		Route::get('/edit', 'AccountController@indexEdit')->name('account.edit');
		Route::post('/update', 'AccountController@update')->name('account.update');
		Route::name('account.')->group(function () {
			Route::post('whatsapp', 'AccountController@whatsapp')->name('whatsapp');
			Route::get('password', 'AccountController@password')->name('password');
			Route::patch('password', 'AccountController@patchPassword')->name('password');
			Route::get('logs', 'AccountController@logs')->name('logs');
		});
	});

	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});
	Route::prefix('submissions')->name('submissions.')->group(function () {
		Route::get('pending', 'SubmissionController@pending')->name('pending');
		Route::get('approved', 'SubmissionController@approved')->name('approved');
		Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
		Route::post('print/{id}', 'Admin\SubmissionController@print')->name('print');
		Route::get('show/{id}', 'SubmissionController@show')->name('show');
	});
});

resources/views/admin/layouts/partials/footer-script.blade.php
<!-- JAVASCRIPT -->
<script>var HOST_URL = "{{ url('/') }}";</script>

<script src="{{ URL::asset('assets/libs/jquery/jquery.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/bootstrap/bootstrap.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/metismenu/metismenu.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/simplebar/simplebar.min.js') }}"></script>
<script src="{{ URL::asset('assets/libs/node-waves/node-waves.min.js') }}"></script>
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

@yield('script')

<!-- App js -->
<script src="{{ URL::asset('assets/js/app.min.js') }}"></script>

@yield('script-bottom')

resources/views/admin/layouts/partials/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                © <script>
                    document.write(new Date().getFullYear())

                </script> {{ config('app.name') }}<span class="d-none d-sm-inline-block"></span>
            </div>
        </div>
    </div>
</footer>

resources/views/admin/layouts/partials/head.blade.php
@yield('css')

<!-- App css -->
<link href="{{ URL::asset('assets/css/bootstrap-dark.min.css')}}" id="bootstrap-dark" rel="stylesheet"
    type="text/css" />
<link href="{{ URL::asset('assets/css/bootstrap.min.css')}}" id="bootstrap-light" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/css/icons.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/css/app-rtl.min.css')}}" id="app-rtl" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/css/app-dark.min.css')}}" id="app-dark" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/css/app.min.css')}}" id="app-light" rel="stylesheet" type="text/css" />
<link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

resources/views/admin/layouts/partials/right-sidebar.blade.php
<!-- Right Sidebar -->
<div class="right-bar">
    <div data-simplebar class="h-100">
        <div class="rightbar-title px-3 py-4">
            <a href="javascript:void(0);" class="right-bar-toggle float-right">
                <i class="mdi mdi-close noti-icon"></i>
            </a>
            <h5 class="m-0">Settings</h5>
        </div>

        <!-- Settings -->
        <hr class="mt-0" />
        <h6 class="text-center">Choose Layouts</h6>

        <div class="p-4">
            <div class="mb-2">
                <img src="{{ asset('assets/images/layouts/layout-1.jpg') }}" class="img-fluid img-thumbnail" alt="">
            </div>
            <div class="custom-control custom-switch mb-3">
                <input type="checkbox" class="custom-control-input theme-choice" id="light-mode-switch" checked />
                <label class="custom-control-label" for="light-mode-switch">Light Mode</label>
            </div>

            <div class="mb-2">
                <img src="{{ asset('assets/images/layouts/layout-2.jpg') }}" class="img-fluid img-thumbnail" alt="">
            </div>
            <div class="custom-control custom-switch mb-3">
                <input type="checkbox" class="custom-control-input theme-choice" id="dark-mode-switch"
                    data-bsStyle="assets/css/bootstrap-dark.min.css" data-appStyle="assets/css/app-dark.min.css" />
                <label class="custom-control-label" for="dark-mode-switch">Dark Mode</label>
            </div>

            <div class="mb-2">
                <img src="{{ asset('assets/images/layouts/layout-3.jpg') }}" class="img-fluid img-thumbnail" alt="">
            </div>
            <div class="custom-control custom-switch mb-5">
                <input type="checkbox" class="custom-control-input theme-choice" id="rtl-mode-switch"
                    data-appStyle="assets/css/app-rtl.min.css" />
                <label class="custom-control-label" for="rtl-mode-switch">RTL Mode</label>
            </div>

        </div>

    </div> <!-- end slimscroll-menu-->
</div>
<!-- /Right-bar -->

resources/views/admin/layouts/partials/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="vertical-menu">

    <div data-simplebar class="h-100">

        <!--- Sidemenu -->
        <div id="sidebar-menu">
            <!-- Left Menu Start -->
            <ul class="metismenu list-unstyled" id="side-menu">
                <li class="menu-title">Main</li>

                <li>
                    <a href="{{ route('admin.home') }}" class="waves-effect">
                        <i class="ti-home"></i>
                        <span>Dashboard</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.formsurat') }}" class="waves-effect">
                        <i class="ti-pencil-alt"></i>
                        <span>Form Surat</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="ti-email"></i>
                        <span>Layanan Surat Masuk</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li><a href="{{ route('admin.submissions.pending') }}">
                                <span
                                    class="badge badge-pill badge-primary float-right">{{ pendingSubmissions() }}</span>
                                Menunggu Persetujuan </a></li>
                        <li><a href="{{ route('admin.submissions.approved') }}">Disetujui</a></li>
                        <li><a href="{{ route('admin.submissions.rejected') }}">Ditolak</a></li>
                        <li><a href="{{ route('admin.submissions.selesai') }}">Selesai</a></li>
                    </ul>
                </li>
                <li>
                    <a href="{{ route('admin.pencatatan') }}" class="waves-effect">
                        <i class="ti-pencil-alt"></i>
                        <span>Pencatatan Surat</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="ti-folder"></i>
                        <span>Arsip Surat</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li>
                            <a href="#" class="has-arrow waves-effect">
                                <i class="ti-download"></i>
                                <span>Surat Masuk Pemerintahan</span>
                            </a>
                            <ul class="sub-menu" aria-expanded="false">

                                <!--<a href="{{ route('admin.arsip', 'umum') }}" class="waves-effect">Gobi Surat Masuk-->
                                <!--    Umum</a>-->
                                <a href="{{ route('admin.arsip', 'pemerintahan') }}" class="waves-effect">Gobi Surat
                                    Masuk Pemerintahan</a>

                            </ul>
                        </li>
                        <li>
                            <a href="#" class="has-arrow waves-effect">
                                <i class="ti-upload"></i>
                                <span>Surat Keluar Masyarakat</span>
                            </a>
                            <ul class="sub-menu" aria-expanded="false">
                                @foreach (lettersAll() as $item)
                                    @if ($item->id == 4)
                                        <a href="{{ route('admin.arsip.out.q', 1) }}" class="waves-effect">Gobi
                                            Surat Keterangan E-KTP</a>
                                        <a href="{{ route('admin.arsip.out.q', 2) }}" class="waves-effect">Gobi
                                            Surat Keterangan Akta Kelahiran</a>
                                    @endif
                                    @if ($item->id != 4)
                                        <a href="{{ route('admin.arsip.out', $item->id) }}"
                                            class="waves-effect">Gobi {{ $item->name }}</a>
                                    @endif
                                @endforeach
                                <a href="{{ route('admin.arsip', 'keluar-pemerintahan') }}" class="waves-effect">Gobi Surat
                                    Keluar Pemerintahan</a>
                            </ul>
                        </li>
                    </ul>
                </li>

                <li class="menu-title">Master Data</li>
                <li>
                    <a href="{{ route('admin.data.index') }}" class=" waves-effect">

                        <i class="ti-user"></i>
                        <span>Data User</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.users.index') }}" class=" waves-effect">
                        @if (pendingUsers() > 0)
                            <span class="badge badge-pill badge-primary float-right">{{ pendingUsers() }}</span>
                        @endif

                        <i class="ti-agenda"></i>
                        <span>Data Warga</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.letters.index') }}" class=" waves-effect">
                        <i class="ti-receipt"></i>
                        <span>Daftar Surat</span>
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.signatories.index') }}" class=" waves-effect">
                        <i class="ti-user"></i>
                        <span>Data Kepala Desa</span>
                    </a>
                </li>
                <li>
                    <a href="javascript: void(0);" class="has-arrow waves-effect">
                        <i class="ti-files"></i>
                        <span>Laporan</span>
                    </a>
                    <ul class="sub-menu" aria-expanded="false">
                        <li>
                            @foreach (lettersAll() as $item)
                                @if ($item->id == 4)
                                    <a href="{{ route('admin.laporan.q', 1) }}" class=" waves-effect">
                                        <span>Laporan Surat Keterangan E-KTP</span>
                                    </a>
                                    <a href="{{ route('admin.laporan.q', 2) }}" class=" waves-effect">
                                        <span>Laporan Surat Keterangan Akta Kelahiran</span>
                                    </a>
                                @endif
                                @if ($item->id != 4)
                                    <a href="{{ route('admin.laporan', $item->id) }}" class=" waves-effect">
                                        <span>Laporan {{ $item->name }}</span>
                                    </a>
                                @endif
                                
                               
                            @endforeach
                            <!--<a href="{{ route('admin.laporan.masuk', 'umum') }}" class=" waves-effect">-->
                            <!--    <span>Laporan Surat Masuk Umum</span>-->
                            <!--</a>-->
                            <a href="{{ route('admin.laporan.masuk', 'pemerintahan') }}" class=" waves-effect">
                                <span>Laporan Surat Masuk Pemerintahan</span>
                            </a>
                            <a href="{{ route('admin.laporan.masuk', 'keluar-pemerintahan') }}" class=" waves-effect">
                                <span>Laporan Surat Keluar Pemerintahan</span>
                            </a>
                        </li>

                    </ul>
                </li>
                {{-- <li>
                    <a href="{{ route('admin.helpers') }}" class=" waves-effect">
                        <i class="ti-hand-point-right"></i>
                        <span>Helpers</span>
                    </a>
                </li> --}}
            </ul>
        </div>
        <!-- Sidebar -->
    </div>
</div>
<!-- Left Sidebar End -->

resources/views/admin/layouts/partials/topbar.blade.php
<header id="page-topbar">
    <div class="navbar-header">
        <div class="d-flex">
            <div class="navbar-brand-box" style="background-color: #4F5551 !important ">
                <a href="{{ route('admin.home') }}" class="logo logo-dark">
                    <span class="logo-sm">
                        <img src="{{ asset('assets/images/logo.svg') }}" alt="" height="22">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('assets/images/logo-dark.png') }}" alt="" height="17">
                    </span>
                </a>

                <a href="{{ route('admin.home') }}" class="logo logo-light">
                    <span class="logo-sm">
                        <img src="{{ asset('frontend/logo.jpg') }}" alt="" height="50">
                    </span>
                    <span class="logo-lg">
                        <img src="{{ asset('frontend/logo.jpg') }}" alt="" height="50">
                    </span>
                </a>
                {{-- <a href="index" style="color: white" class="logo logo-light">
                    <span class="logo-sm">
                        <h2>Desa Parit Baru</h2>
                    </span>
                    <span class="logo-lg">
                        <h2>Desa Parit Baru</h2>
                    </span>
                </a> --}}
            </div>
            <button type="button" class="btn btn-sm px-3 font-size-24 header-item waves-effect" id="vertical-menu-btn">
                <i class="mdi mdi-menu"></i>
            </button>
        </div>

        <div class="d-flex">
            <div class="dropdown d-none d-lg-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect" data-toggle="fullscreen">
                    <i class="mdi mdi-fullscreen"></i>
                </button>
            </div>

            <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item waves-effect" id="page-header-user-dropdown"
                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <img class="rounded-circle header-profile-user" src="{{ asset(auth('admin')->user()->photo) }}"
                        alt="{{ asset(auth('admin')->user()->name) }}">
                </button>
                <div class="dropdown-menu dropdown-menu-right">
                    <!-- item-->
                    <a class="dropdown-item" href="{{ route('admin.account') }}"><i
                            class="mdi mdi-account-badge-outline font-size-17 align-middle mr-1"></i> Account</a>
                    <a class="dropdown-item" href="{{ route('admin.account.password') }}"><i
                            class="mdi mdi-shield-alert-outline font-size-17 align-middle mr-1"></i> Change Password</a>
                    <a class="dropdown-item" href="{{ route('admin.account.logs') }}"><i
                            class="mdi mdi-format-list-bulleted-square font-size-17 align-middle mr-1"></i> Log
                        Activity</a>
                    {{-- <a class="dropdown-item d-block" href="{{ route('admin.settings') }}"><i
                            class="mdi mdi-settings font-size-17 align-middle mr-1"></i> Settings</a> --}}
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item text-danger" href="javascript:void();"
                        onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                        <i class="mdi mdi-logout font-size-17 align-middle mr-1 text-danger"></i>
                        {{ __('Logout') }}
                    </a>
                    <form id="logout-form" action="{{ route('admin.logout') }}" method="POST" style="display: none;">
                        @csrf
                    </form>
                </div>
            </div>

            {{-- <div class="dropdown d-inline-block">
                <button type="button" class="btn header-item noti-icon waves-effect">
                    <i class="mdi mdi-settings-outline"></i>
                </button>
            </div> --}}

        </div>
    </div>
</header>