routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin Routes
Route::patch('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status');
Route::get('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status.get');


Route::prefix(config('app.admin_path'))->name('admin.')->namespace('Admin')->group(function () {
	Route::get('/', function () {
		return redirect()->route('admin.home');
	});

	Route::get('login', 'AuthController@index')->name('login');
	Route::post('login', 'AuthController@login')->name('login');
	Route::post('logout', 'AuthController@logout')->name('logout');

	Route::prefix('form-surat')->group(function () {
		Route::get('/', 'FormSuratController@index')->name('formsurat');
		Route::post('store/{letter}', 'FormSuratController@store')->name('formsurat.store');
	});

	Route::prefix('pencatatan')->group(function () {
		Route::get('/', 'PencatatanSuratController@index')->name('pencatatan');
		Route::post('store', 'PencatatanSuratController@store')->name('pencatatan.store');
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::post('cetaks', 'LaporanController@cetakPemerintahan')->name('laporan.cetak.kpemerintahan');
		Route::post('cetak/masuk', 'LaporanController@cetakMasuk')->name('laporan.cetak.masuk');

		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});

	Route::middleware('auth:admin')->group(function () {
		Route::get('home', 'HomeController@index')->name('home');

		Route::prefix('submissions')->name('submissions.')->group(function () {
			Route::get('pending', 'SubmissionController@pending')->name('pending');
			Route::get('approved', 'SubmissionController@approved')->name('approved');
			Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
			Route::post('approved/export', 'SubmissionController@exportApproved')->name('approved.export');
			Route::get('rejected', 'SubmissionController@rejected')->name('rejected');
			Route::get('show/{id}', 'SubmissionController@show')->name('show');

			Route::patch('update/{id}', 'SubmissionController@update')->name('update');
			Route::post('print/{id}', 'SubmissionController@print')->name('print');
		});

		Route::resource('data', 'AdminController');
		Route::resource('users', 'UserController');
		Route::resource('letters', 'LetterController');
		Route::resource('signatories', 'SignatoryController');
		Route::view('helpers', 'admin.helper.index')->name('helpers');

		Route::prefix('user')->group(function () {
			Route::get('approval/{status}/{id}', 'UserController@approval')->name('user.approval');
		});

		Route::prefix('import')->name('import.')->group(function () {
			Route::post('data', 'ImportController@admin')->name('data');
			Route::post('users', 'ImportController@user')->name('users');
		});

		Route::prefix('account')->group(function () {
			Route::get('/', 'AccountController@index')->name('account');
			Route::patch('/', 'AccountController@update')->name('account');
			Route::name('account.')->group(function () {
				Route::get('password', 'AccountController@password')->name('password');
				Route::patch('password', 'AccountController@patchPassword')->name('password');
				Route::get('logs', 'AccountController@logs')->name('logs');
			});
		});

		Route::prefix('settings')->name('settings')->group(function () {
			Route::get('/', 'SettingController@index');
			Route::patch('/', 'SettingController@update');
		});

		Route::prefix('datatables')->name('datatables.')->group(function () {
			Route::post('users', 'DataController@users')->name('users');
			Route::post('submissions/pending', 'DataController@submissionsPending')->name('submissions.pending');
			Route::post('submissions/approved', 'DataController@submissionsApproved')->name('submissions.approved');
			Route::post('submissions/rejected', 'DataController@submissionsRejected')->name('submissions.rejected');
			Route::post('submissions/selesai', 'DataController@submissionSelesai')->name('submissions.selesai');
		});
	});
});

// User Routes
Route::get('/', 'HomeController@index2');

Route::get('login', 'AuthController@index')->name('login');
Route::get('registrasi', 'AuthController@registrasi')->name('registrasi');
Route::post('registrasi', 'AuthController@registrasiStore')->name('registrasi.store');
Route::post('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@login')->name('login');
Route::post('lupa-password', 'AuthController@lupaPassword')->name('lupa');
Route::post('lupa-password-proses/{id}', 'AuthController@lupaPasswordProses')->name('lupa.proses');
Route::get('reset-password/{token}', 'AuthController@resetPassword')->name('reset.password');
Route::post('logout', 'AuthController@logout')->name('logout');

Route::middleware('auth')->group(function () {
	Route::get('home', 'HomeController@index')->name('home');
	Route::get('submissions', 'SubmissionController@index')->name('submissions.index');
	Route::get('submissions/add', 'SubmissionController@add')->name('submissions.add');
	Route::post('submissions/store/{letter}', 'SubmissionController@store')->name('submissions.store');

	Route::prefix('account')->group(function () {
		Route::get('/', 'AccountController@index')->name('account');
		Route::get('/edit', 'AccountController@indexEdit')->name('account.edit');
		Route::post('/update', 'AccountController@update')->name('account.update');
		Route::name('account.')->group(function () {
			Route::post('whatsapp', 'AccountController@whatsapp')->name('whatsapp');
			Route::get('password', 'AccountController@password')->name('password');
			Route::patch('password', 'AccountController@patchPassword')->name('password');
			Route::get('logs', 'AccountController@logs')->name('logs');
		});
	});

	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});
	Route::prefix('submissions')->name('submissions.')->group(function () {
		Route::get('pending', 'SubmissionController@pending')->name('pending');
		Route::get('approved', 'SubmissionController@approved')->name('approved');
		Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
		Route::post('print/{id}', 'Admin\SubmissionController@print')->name('print');
		Route::get('show/{id}', 'SubmissionController@show')->name('show');
	});
});

app/Http/Controllers/Admin/SubmissionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Http;
use App\Submission;
use App\Signatory;
use App\Signatories;
use App\Exports\SubmissionsExport;
use Activity;
use App\Letter;
use Excel;
use Illuminate\Support\Facades\Mail;
use PhpParser\Lexer;

class SubmissionController extends Controller
{
    public function pending()
    {
        $submissions = Submission::with('user', 'letter')
            ->where('approval_status', 0)
            ->orderBy('created_at', 'desc')
            ->get();

        return view('admin.submission.pending', ['submissions' => $submissions]);
    }

    public function approved()
    {
        $submissions = Submission::with('user', 'letter', 'admin')
            ->where('approval_status', 1)
            ->orderBy('created_at', 'desc')
            ->get();

        return view('admin.submission.approved', ['submissions' => $submissions]);
    }

    public function exportApproved()
    {
        return Excel::download(new SubmissionsExport, 'Surat Yang Disetujui ' . now()->format('d-M-Y') . '.xlsx');
    }

    public function rejected()
    {
        $submissions = Submission::with('user', 'letter', 'admin')
            ->where('approval_status', 2)
            ->orderBy('created_at', 'desc')
            ->get();

        return view('admin.submission.rejected', ['submissions' => $submissions]);
    }
    public function selesai()
    {
        $submissions = Submission::with('user', 'letter', 'admin')
            ->where('approval_status', 3)
            ->orderBy('created_at', 'desc')
            ->get();

        return view('admin.submission.selesai', ['submissions' => $submissions]);
    }

    public function show($id)
    {
       
        $submission = Submission::find($id);
        $signatories = Signatory::all();
        $letter = Letter::findOrFail($submission->letter_id);
        $awalan = $letter->number_format . '/';
        $query = Submission::select('number')->where('number','!=',null)->where('letter_id', $letter->id)->orderBy('number', 'desc');

        $lebar = 1;
        $jumlahrecord = $query->count();

        if ($jumlahrecord == 0) {
            $nomor = 1;
        } else {
            $row = $query->get()->toArray();
            $nomor = intval(substr($row[0]['number'], strlen($awalan))) + 1;
        }

        if ($lebar > 0)
            $angka = $awalan . str_pad($nomor, $lebar, "0", STR_PAD_LEFT);
        else
            $angka = $awalan . $nomor;
        $nomor_surat = $angka . '/PEM' . '/' . date('Y');
        // $data['no_surat'] = $nomor_surat;
        return view('admin.submission.show', ['submission' => $submission, 'signatories' => $signatories,'no_surat' => $nomor_surat]);
    }

    public function status($id, $status, Request $request)
    {
        $submission = Submission::find($id);
        $submission->approval_status = $status;
        $submission->approval_at = now();
        $submission->admin_id = 1;
        if ($status == 2) {
            $submission->notes = $request->notes;
        }


        if ($status == 1) {
            $letter = $submission->letter;
            $awalan = $letter->number_format . '/';
            $query = Submission::select('number')->where('letter_id', $letter->id)->orderBy('number', 'desc');

            $lebar = 1;
            $jumlahrecord = $query->count();

            if ($jumlahrecord == 0) {
                $nomor = 1;
            } else {
                $row = $query->get()->toArray();
                $nomor = intval(substr($row[0]['number'], strlen($awalan))) + 1;
            }

            if ($lebar > 0)
                $angka = $awalan . str_pad($nomor, $lebar, "0", STR_PAD_LEFT);
            else
                $angka = $awalan . $nomor;




            $nomor_surat = $angka . '/PEM' . '/'.'IX/' . date('Y');

            $submission->number =  $nomor_surat;
            $messages = 'Pengajuan surat "' . $submission->letter->name . '" Bernomor ' . $submission->number . ' oleh: ' . $submission->user->name . ' telah disetujui. Silakan datang ke Kantor Desa dengan Menggunakan Masker!';
            $redirect_route = route('admin.submissions.approved');
            $subject = 'Surat Disetujui';
        } elseif ($status == 3) {
            $messages = 'Pengajuan surat "' . $submission->letter->name . '" Bernomor ' . $submission->number . ' oleh: ' . $submission->user->name . ' telah ditandatangani dan dinyatakan selesai.';
            $redirect_route = route('submissions.selesai');
            $subject = 'Surat Selesai';
        } else {
            $messages = 'Pengajuan "' . $submission->letter->name . '" Bernomor ' . $submission->number . ' oleh: ' . $submission->user->name . ' telah ditolak!';
            $redirect_route = route('admin.submissions.rejected');
            $subject = 'Surat Ditolak';
        }
        $submission->save();

        $data['submission'] = $submission;
        $data['messages'] = $messages;
        $email = [$submission->user->email];
        // return view('email.submission_approval',$data);

        Mail::send('email.submission_approval', $data, function ($message) use ($email, $subject) {
            $message->to($email)->subject($subject);
        });

        // $response = Http::withHeaders(['Authorization' => config('whatsapp.token')])
        // ->asForm()
        // ->post('https://fonnte.com/api/send_message.php', [
        //     'phone' => $submission->user->phone_number,
        //     'type' => 'text',
        //     'text' => $message
        // ]);

        Activity::add(['page' => 'Warga', 'description' => 'Berhasil Mengubah Status Pengajuan Surat: #' . $id]);

        // $route = $status == 1 ?  : route('admin.submissions.rejected');
        return redirect($redirect_route)->with([
            'status' => 'success',
            'message' => 'Mengubah Status Pengajuan Surat: #' . $id
        ]);
    }

    public function update(Request $request, $id)
    {
        $submission = Submission::find($id);

        $data_old = json_decode($submission->data,true);

        // dd($data_old);
        
        $file_old = [];
        foreach($data_old as $key => $do){
            if (strpos($key, 'file') !== false || strpos($key, 'foto') !== false) {
                $file_old[$key] = $do;
            }
        }

        $new_data = $request->except('_token', '_method', 'number');
        $arr_merge = array_merge($new_data,$file_old);

        $submission->number = $request->number;
        $submission->data = json_encode($arr_merge);
        $submission->save();

        Activity::add(['page' => 'Kaur Umum', 'description' => 'Berhasil Memperbarui Pengajuan Surat: #' . $id]);

        return back()->with([
            'status' => 'success',
            'message' => 'Memperbarui Pengajuan Surat: #' . $id
        ]);
    }

    public function print($id, Request $request)
    {
        $submission = Submission::find($id);

        $signatory_id = $request->signatory ?? setting('signatory_active');
        $signatory = Signatory::where('is_active', 1)->first();

        $data['signatory_name'] = $signatory->name;
        $data['signatory_position'] = $signatory->position;
        $data['on_behalf'] = $signatory_id != 1 ? 'A/N, Perbengkel ' . ucwords(strtolower(setting('village'))) : '';

        foreach ($submission->user->toArray() as $key => $value) {
            $data[$key] = $value;
        }

        $data['ttl'] = $submission->user->getPsb();
        $data['tgl'] = now()->formatLocalized('%d %B %Y');
        $data['districts'] = ucwords(strtolower(setting('districts')));
        $data['sub-districts'] = ucwords(strtolower(setting('sub-districts')));
        $data['village'] = ucwords(strtolower(setting('village')));

        foreach (json_decode($submission->data) as $key => $value) {
            $data[$key] = $value;
        }

        $content = $submission->letter->content;
        foreach ($data as $key => $value) {
            $content = str_replace('[' . $key . ']', $value, $content);
            if($submission->letter_id == 4){
                $fix = $submission->keterangan_pengajuan == 1 ? 'Belum pernah melakukan perekaman E-KTP dan tidak memiliki E-KTP' : 'Belum Memiliki Akta Kelahiran' ;
                 $content = str_replace('[keterangan_pengajuan]', $fix, $content);
            }
        }

        return view('admin.print.template', ['submission' => $submission, 'content' => $content]);
    }
}

resources/views/submissions/approved.blade.php
@extends('layouts.master')

@section('title', 'Pengajuan Surat: Disetujui')

@section('css')
    <link href="{{ URL::asset('assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            @component('components.breadcumb')
                @slot('title')
                    Pengajuan Surat: Disetujui
                @endslot
                @slot('li_1')
                    Admin
                @endslot
            @endcomponent
        </div>
        <div class="col-sm-6">
            <!--<div class="float-right d-md-block mb-3">-->
            <!--    <div class="dropdown">-->
            <!--        <button class="btn btn-primary dropdown-toggle waves-effect waves-light" type="button"-->
            <!--            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
            <!--            <i class="mdi mdi-gesture-spread mr-2"></i> Action-->
            <!--        </button>-->
            <!--        <div class="dropdown-menu dropdown-menu-right">-->
            <!--            <form method="POST" action="{{ route('admin.submissions.approved.export') }}">-->
            <!--                @csrf-->
            <!--                <button type="submit" class="dropdown-item">Export</button>-->
            <!--            </form>-->
            <!--        </div>-->
            <!--    </div>-->
            <!--</div>-->
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Pengajuan Surat: Disetujui</h4>
                    @include('admin.components.message')
                    <table id="datatable" class="table table-bordered dt-responsive nowrap"
                        style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Waktu Pengajuan</th>
                                <th>Nomor Surat</th>
                                <th>Nama</th>
                                <th>Jenis Surat</th>
                                <th>Kepentingan</th>
                                <th>Waktu Penyetujuan</th>
                                <th>Disetujui Oleh</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($submissions as $key => $submission)
                            @php
                                if($submission->kepentingan != 'Diri Sendiri'){
                                    $nama_ = json_decode($submission->data)->nama_lengkap;
                                }
                            @endphp
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $submission->created_at->formatLocalized('%d %B %Y %H:%M') }}</td>
                                    <td>{{ $submission->number ?? '-' }}</td>
                                    <td>{{ $submission->user->name }}</td>
                                    <td>{{ $submission->letter->name }} {{ $submission->letter->id == 4 ? $submission->keterangan_pengajuan == 1 ? '(Belum pernah melakukan perekaman E-KTP dan tidak memiliki E-KTP)' : '(Belum memiliki Akta Kelahiran)' : '' }}</td>
                                    <td>Untuk {{ $submission->kepentingan }} {{ $submission->kepentingan != 'Diri Sendiri' ? ' : ' . $nama_  : '' }}</td>
                                    <td>{{ $submission->approval_at->formatLocalized('%d %B %Y %H:%M') }}</td>
                                    <td>{{ $submission->admin->name }}</td>

                                    <td>
                                        <form method="POST"
                                            action="{{ route('admin.submissions.print', [$submission->id]) }}"
                                            class="d-inline" target="_blank">
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-warning waves-effect waves-light"><i
                                                    class="mdi mdi-printer-check"></i> Cetak</button>
                                        </form>
                                        <button onclick="ttd(this)"
                                            data-url="{{ route('admin.submissions.status.get', [$submission->id, 3]) }}"
                                            type="submit" class="btn btn-sm btn-success waves-effect waves-light"><i
                                                class="mdi mdi-signature-freehand"></i> Tanda Tangan</button>
                                        <a class="btn btn-sm btn-info waves-effect waves-light"
                                            href="{{ route('admin.submissions.show', $submission->id) }}"
                                            role="button"><i class="mdi mdi mdi-eye-circle"></i> Detail</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')

    <!-- Plugins js -->
    <script src="{{ URL::asset('assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.js') }}"></script>
    <script src="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>

    <script src="{{ URL::asset('assets/js/pages/datatables.init.js') }}"></script>
    <script src="{{ URL::asset('assets/js/pages/lightbox.init.js') }}"></script>

    <script type="text/javascript">
        $(document).on('submit', '.form-delete', function(e) {
            var form = this;
            e.preventDefault();
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#34c38f",
                cancelButtonColor: "#f46a6a",
                confirmButtonText: "Ya!"
            }).then(function(result) {
                if (result.value) {
                    return form.submit();
                }
            });
        });

        function ttd(obj) {
            let url = $(obj).attr('data-url');
            console.log(url);
            Swal.fire({
                title: "Yakin?",
                text: "Surat akan dinyatakan selesai",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#34c38f",
                cancelButtonColor: "#f46a6a",
                confirmButtonText: "Ya!"
            }).then(function(result) {
                if (result.value) {
                    window.location.href = url;
                }
            });
        }
    </script>

@endsection

resources/views/submissions/selesai.blade.php
@extends('layouts.master')

@section('title', 'Pengajuan Surat: Selesai')

@section('css')
    <link href="{{ URL::asset('assets/libs/datatables/datatables.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.css') }}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

    <!-- start page title -->
    <div class="row align-items-center">
        <div class="col-sm-6">
            @component('components.breadcumb')
                @slot('title')
                    Pengajuan Surat: Selesai
                @endslot
                @slot('li_1')
                    Admin
                @endslot
            @endcomponent
        </div>
    </div>
    <!-- end page title -->

    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">

                    <h4 class="card-title">Pengajuan Surat: Selesai</h4>
                    @include('components.message')
                    <table id="datatable" class="table table-bordered dt-responsive nowrap"
                        style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Waktu Pengajuan</th>
                                <th>Nama</th>
                                <th>Jenis Surat</th>
                                <th>Kepentingan</th>
                                <th>Waktu Selesai</th>
                                <th>Selesai Oleh</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($submissions as $key => $submission)
                                @php
                                    if ($submission->kepentingan != 'Diri Sendiri') {
                                        $nama_ = json_decode($submission->data)->nama_lengkap;
                                    }
                                @endphp
                                <tr>
                                    <td>{{ $key + 1 }}</td>
                                    <td>{{ $submission->created_at->formatLocalized('%d %B %Y %H:%M') }}</td>
                                    <td>{{ $submission->user->name }}</td>
                                    <td>{{ $submission->letter->name }}
                                        {{ $submission->letter->id == 4 ? ($submission->keterangan_pengajuan == 1 ? '(Belum pernah melakukan perekaman E-KTP dan tidak memiliki E-KTP)' : '(Belum memiliki Akta Kelahiran)') : '' }}
                                    </td>
                                    <td>Untuk {{ $submission->kepentingan }} {{ $submission->kepentingan != 'Diri Sendiri' ? ' : ' . $nama_  : '' }}</td>
                                    <td>{{ $submission->approval_at->formatLocalized('%d %B %Y %H:%M') }}</td>
                                    <td>{{ $submission->admin->name }}</td>
                                    <td>
                                        <form method="POST"
                                            action="{{ route('submissions.print', [$submission->id]) }}"
                                            class="d-inline" target="_blank">
                                            @csrf
                                            <button type="submit" class="btn btn-sm btn-warning waves-effect waves-light"><i
                                                    class="mdi mdi-printer-check"></i> Cetak</button>
                                        </form>
                                        <a class="btn btn-sm btn-info waves-effect waves-light"
                                            href="{{ route('submissions.show', $submission->id) }}"
                                            role="button"><i class="mdi mdi mdi-eye-circle"></i> Detail</a>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>

                </div>
            </div>
        </div> <!-- end col -->
    </div> <!-- end row -->

@endsection

@section('script')

    <!-- Plugins js -->
    <script src="{{ URL::asset('assets/libs/datatables/datatables.min.js') }}"></script>
    <script src="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.js') }}"></script>
    <script src="{{ URL::asset('assets/libs/sweetalert2/sweetalert2.min.js') }}"></script>

    <script src="{{ URL::asset('assets/js/pages/datatables.init.js') }}"></script>
    <script src="{{ URL::asset('assets/js/pages/lightbox.init.js') }}"></script>

    <script type="text/javascript">
        $(document).on('submit', '.form-delete', function(e) {
            var form = this;
            e.preventDefault();
            Swal.fire({
                title: "Are you sure?",
                text: "You won't be able to revert this!",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#34c38f",
                cancelButtonColor: "#f46a6a",
                confirmButtonText: "Yes, delete it!"
            }).then(function(result) {
                if (result.value) {
                    return form.submit();
                }
            });
        });
    </script>

@endsection