routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin Routes
Route::patch('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status');
Route::get('status/{id}/{status}', 'Admin\SubmissionController@status')->name('admin.submissions.status.get');


Route::prefix(config('app.admin_path'))->name('admin.')->namespace('Admin')->group(function () {
	Route::get('/', function () {
		return redirect()->route('admin.home');
	});

	Route::get('login', 'AuthController@index')->name('login');
	Route::post('login', 'AuthController@login')->name('login');
	Route::post('logout', 'AuthController@logout')->name('logout');

	Route::prefix('form-surat')->group(function () {
		Route::get('/', 'FormSuratController@index')->name('formsurat');
		Route::post('store/{letter}', 'FormSuratController@store')->name('formsurat.store');
	});

	Route::prefix('pencatatan')->group(function () {
		Route::get('/', 'PencatatanSuratController@index')->name('pencatatan');
		Route::post('store', 'PencatatanSuratController@store')->name('pencatatan.store');
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::post('cetaks', 'LaporanController@cetakPemerintahan')->name('laporan.cetak.kpemerintahan');
		Route::post('cetak/masuk', 'LaporanController@cetakMasuk')->name('laporan.cetak.masuk');

		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});

	Route::middleware('auth:admin')->group(function () {
		Route::get('home', 'HomeController@index')->name('home');

		Route::prefix('submissions')->name('submissions.')->group(function () {
			Route::get('pending', 'SubmissionController@pending')->name('pending');
			Route::get('approved', 'SubmissionController@approved')->name('approved');
			Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
			Route::post('approved/export', 'SubmissionController@exportApproved')->name('approved.export');
			Route::get('rejected', 'SubmissionController@rejected')->name('rejected');
			Route::get('show/{id}', 'SubmissionController@show')->name('show');

			Route::patch('update/{id}', 'SubmissionController@update')->name('update');
			Route::post('print/{id}', 'SubmissionController@print')->name('print');
		});

		Route::resource('data', 'AdminController');
		Route::resource('users', 'UserController');
		Route::resource('letters', 'LetterController');
		Route::resource('signatories', 'SignatoryController');
		Route::view('helpers', 'admin.helper.index')->name('helpers');

		Route::prefix('user')->group(function () {
			Route::get('approval/{status}/{id}', 'UserController@approval')->name('user.approval');
		});

		Route::prefix('import')->name('import.')->group(function () {
			Route::post('data', 'ImportController@admin')->name('data');
			Route::post('users', 'ImportController@user')->name('users');
		});

		Route::prefix('account')->group(function () {
			Route::get('/', 'AccountController@index')->name('account');
			Route::patch('/', 'AccountController@update')->name('account');
			Route::name('account.')->group(function () {
				Route::get('password', 'AccountController@password')->name('password');
				Route::patch('password', 'AccountController@patchPassword')->name('password');
				Route::get('logs', 'AccountController@logs')->name('logs');
			});
		});

		Route::prefix('settings')->name('settings')->group(function () {
			Route::get('/', 'SettingController@index');
			Route::patch('/', 'SettingController@update');
		});

		Route::prefix('datatables')->name('datatables.')->group(function () {
			Route::post('users', 'DataController@users')->name('users');
			Route::post('submissions/pending', 'DataController@submissionsPending')->name('submissions.pending');
			Route::post('submissions/approved', 'DataController@submissionsApproved')->name('submissions.approved');
			Route::post('submissions/rejected', 'DataController@submissionsRejected')->name('submissions.rejected');
			Route::post('submissions/selesai', 'DataController@submissionSelesai')->name('submissions.selesai');
		});
	});
});

// User Routes
Route::get('/', 'HomeController@index2');

Route::get('login', 'AuthController@index')->name('login');
Route::get('registrasi', 'AuthController@registrasi')->name('registrasi');
Route::post('registrasi', 'AuthController@registrasiStore')->name('registrasi.store');
Route::post('login', 'AuthController@login')->name('login');
Route::post('login', 'AuthController@login')->name('login');
Route::post('lupa-password', 'AuthController@lupaPassword')->name('lupa');
Route::post('lupa-password-proses/{id}', 'AuthController@lupaPasswordProses')->name('lupa.proses');
Route::get('reset-password/{token}', 'AuthController@resetPassword')->name('reset.password');
Route::post('logout', 'AuthController@logout')->name('logout');

Route::middleware('auth')->group(function () {
	Route::get('home', 'HomeController@index')->name('home');
	Route::get('submissions', 'SubmissionController@index')->name('submissions.index');
	Route::get('submissions/add', 'SubmissionController@add')->name('submissions.add');
	Route::post('submissions/store/{letter}', 'SubmissionController@store')->name('submissions.store');

	Route::prefix('account')->group(function () {
		Route::get('/', 'AccountController@index')->name('account');
		Route::get('/edit', 'AccountController@indexEdit')->name('account.edit');
		Route::post('/update', 'AccountController@update')->name('account.update');
		Route::name('account.')->group(function () {
			Route::post('whatsapp', 'AccountController@whatsapp')->name('whatsapp');
			Route::get('password', 'AccountController@password')->name('password');
			Route::patch('password', 'AccountController@patchPassword')->name('password');
			Route::get('logs', 'AccountController@logs')->name('logs');
		});
	});

	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
	});

	Route::prefix('archieve')->group(function () {
		Route::prefix('in')->group(function () {
			Route::get('{cat}', 'ArsipController@index')->name('arsip');
			Route::get('detail/{id}', 'ArsipController@detail')->name('arsip.detail');
		});
		Route::prefix('out')->group(function () {
			Route::get('{letter}', 'ArsipController@indexOut')->name('arsip.out');
			Route::get('q/{keterangan}', 'ArsipController@indexOutQ')->name('arsip.out.q');
			Route::get('detail/{id}', 'ArsipController@detailOut')->name('arsip.out.detail');
		});
	});
	Route::prefix('laporan')->group(function () {
		Route::get('{letter}', 'LaporanController@index')->name('laporan');
		Route::post('cetak', 'LaporanController@cetak')->name('laporan.cetak');
		Route::get('masuk/{jenis}', 'LaporanController@indexMasuk')->name('laporan.masuk');
		Route::get('q/{letter}', 'LaporanController@indexQ')->name('laporan.q');
	});
	Route::prefix('submissions')->name('submissions.')->group(function () {
		Route::get('pending', 'SubmissionController@pending')->name('pending');
		Route::get('approved', 'SubmissionController@approved')->name('approved');
		Route::get('selesai', 'SubmissionController@selesai')->name('selesai');
		Route::post('print/{id}', 'Admin\SubmissionController@print')->name('print');
		Route::get('show/{id}', 'SubmissionController@show')->name('show');
	});
});

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    protected $fillable = [
        'photo', 'sin', 'name', 'password', 'birth_place', 'birth_date', 'gender', 'address', 'religion', 'marital_status', 'profession','email'
    ];

    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $casts = [
        'birth_date' => 'date',
    ];

    public function getShortGender()
    {
        return substr($this->gender, 0, 1);
    }

    public function getPsb()
    {
        try {
            return $this->birth_place . ', ' . $this->birth_date->formatLocalized('%d %B %Y');
        } catch (\Throwable $th) {
            return '-';
        }
    }

    public function submissions()
    {
        return $this->hasMany(Submission::class,'user_id','id');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\UserRequest;
use Illuminate\Http\Request;
use App\User;
use App\ActivityLog;
use Carbon\Carbon;
use Activity;
use Hash;
use Illuminate\Support\Facades\Mail;
use Image;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['user'] = User::where('is_signatories', null)->orderBy('is_active', 'asc')->orderBy('name', 'asc')->get();
        return view('admin.user.index', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(UserRequest $request)
    {
        $user = new User;

        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $path = 'uploads/';

            if (!file_exists(public_path($path))) {
                mkdir($path, 666, true);
            }

            $path .= time() . '.' . $file->getClientOriginalExtension();
            $image = Image::make($file)->resize(300, 300);
            $image->save(public_path($path));
            $user->photo = $path;
        }


        $user->sin = $request->sin;
        $user->name = $request->name;

        $password = $request->password ?? Carbon::parse($request->birth_date)->format('d-m-Y');
        $user->password = Hash::make($password);

        $user->birth_place = $request->birth_place;
        $user->birth_date = $request->birth_date;
        $user->gender = $request->gender;
        $user->email = $request->email;
        $user->address = $request->address;
        $user->religion = $request->religion;
        $user->marital_status = $request->marital_status;
        $user->profession = $request->profession;
        $user->phone_number = $request->phone_number;
        $user->is_active = 1;
        $user->save();

        Activity::add(['page' => 'Warga', 'description' => 'Menambah Data Warga: ' . $request->name]);

        return redirect()->route('admin.users.index')->with([
            'status' => 'success',
            'message' => 'Menambahkan Warga Baru: ' . $request->name
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        $logs = ActivityLog::where([
            'user_type' => 'user',
            'user_id' => $user->id,
        ])->get();

        return view('admin.user.show', ['user' => $user, 'logs' => $logs]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('admin.user.edit', ['user' => $user]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UserRequest $request, User $user)
    {
        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $path = 'uploads/' . time() . '.' . $file->getClientOriginalExtension();
            $image = Image::make($file)->resize(300, 300);
            $image->save(public_path($path));
            $user->photo = $path;
        }

        $user->sin = $request->sin;
        $user->name = $request->name;

        if ($request->password) {
            $user->password = Hash::make($request->password);
        }

        $user->birth_place = $request->birth_place;
        $user->birth_date = $request->birth_date;
        $user->gender = $request->gender;
        $user->email = $request->email;
        $user->address = $request->address;
        $user->religion = $request->religion;
        $user->marital_status = $request->marital_status;
        $user->profession = $request->profession;
        $user->phone_number = $request->phone_number;
        $user->save();

        Activity::add(['page' => 'User', 'description' => 'Menmperbarui Data Warga: ' . $user->name]);

        return redirect()->route('admin.users.index')->with([
            'status' => 'success',
            'message' => 'Berhasil Memperbarui Data Warga: ' . $request->name
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        Activity::add(['page' => 'User', 'description' => 'Menghapus Data Warga: ' . $user->name]);
        $user->delete();

        return back()->with(['status' => 'success', 'message' => 'Data Berhasil Dihapus!']);
    }

    public function approval($status, $id)
    {

        $user = User::findOrFail($id);
        if ($status == 'setujui') {
            $flag = 1;
            $messages = 'Selamat akun anda disetujui sebagai warga desa parit baru, klik tombol di bawah untuk mengunjungi website dan Melakukan pengajuan Surat';
            $subject = 'Akun Disetujui';
        } else if ($status == 'tolak') {
            $flag = 2;
            $messages = 'Mohon maaf akun anda ditolak sebagai warga desa parit baru';
            $subject = 'Akun Ditolak';
        }



        $user->is_active = $flag;
        $user->save();


        $data['user'] = $user;
        $data['messages'] = $messages;
        $email = [$user->email];
        // return view('email.user_approval',$data);

        try {
            Mail::send('email.user_approval', $data, function ($message) use ($email) {
                $message->to($email)->subject('Persetujuan Akun');
            });
        } catch (\Throwable $th) {
            //throw $th;
        }



        // die();

        Activity::add(['page' => 'User', 'description' => 'Mengubah status ' .  $user->name]);

        return redirect()->back()->with([
            'status' => 'success',
            'message' => 'Data berhasil di update',
        ]);
    }
}

resources/views/admin/user/create.blade.php
@extends('admin.layouts.master')

@section('title', 'Tambah Data Warga')

@section('content')

<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        @component('admin.components.breadcumb')
        @slot('title') Tambah Data Warga @endslot
        @slot('li_1') Warga @endslot
        @endcomponent
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Tambah Data Warga</h4>
                <p class="card-title-desc">Silahkan isi dengan benar form dibawah.</p>

                @include('admin.components.message')

                <form class="custom-validation" method="POST" action="{{ route('admin.users.store') }}"
                    enctype="multipart/form-data">
                    @csrf
                    <div class="form-group row">
                        <label for="photo" class="col-sm-2 col-form-label">Foto</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="file" name="photo" id="photo">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="sin" class="col-sm-2 col-form-label">NIK *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="sin" id="sin" value="{{ old('sin') }}"
                                data-parsley-type="number" data-parsley-length="[16,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Nama *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="name" id="name" value="{{ old('name') }}"
                                data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="name" class="col-sm-2 col-form-label">Email *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="email" name="email" id="email" value="{{ old('email') }}" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="birth_place" class="col-sm-2 col-form-label">Tempat Lahir *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="birth_place" id="birth_place"
                                value="{{ old('birth_place') }}" data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="birth_date" class="col-sm-2 col-form-label">Tanggal Lahir *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="date" name="birth_date" id="birth_date"
                                value="{{ old('birth_date') }}" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="gender" class="col-sm-2 col-form-label">Jenis Kelamin</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="gender" id="gender" required>
                                <option selected disabled>Select *</option>
                                <option {{ old('gender') == 'Laki - Laki' ? 'selected' : '' }} value="Laki - Laki">Laki
                                    - Laki</option>
                                <option {{ old('gender') == 'Perempuan' ? 'selected' : '' }} value="Perempuan">Perempuan
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="address" class="col-sm-2 col-form-label">Alamat</label>
                        <div class="col-sm-10">
                            <textarea id="address" name="address" class="form-control" maxlength="225"
                                rows="3"></textarea>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="religion" class="col-sm-2 col-form-label">Agama</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="religion" id="religion" required>
                                <option selected disabled>Select *</option>
                                <option {{ old('religion') == 'Islam' ? 'selected' : '' }} value="Islam">Islam</option>
                                <option {{ old('religion') == 'Protestan' ? 'selected' : '' }} value="Protestan">
                                    Protestan</option>
                                <option {{ old('religion') == 'Katolik' ? 'selected' : '' }} value="Katolik">Katolik
                                </option>
                                <option {{ old('religion') == 'Hindu' ? 'selected' : '' }} value="Hindu">Hindu</option>
                                <option {{ old('religion') == 'Buddha' ? 'selected' : '' }} value="Buddha">Buddha
                                </option>
                                <option {{ old('religion') == 'Konghucu' ? 'selected' : '' }} value="Konghucu">Konghucu
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="marital_status" class="col-sm-2 col-form-label">Status Perkawinan</label>
                        <div class="col-sm-10">
                            <select class="form-control" name="marital_status" id="marital_status" required>
                                <option selected disabled>Select *</option>
                                <option {{ old('marital_status') == 'Belum Kawin' ? 'selected' : '' }}
                                    value="Belum Kawin">Belum Kawin</option>
                                <option {{ old('marital_status') == 'Kawin' ? 'selected' : '' }} value="Kawin">Kawin
                                </option>
                            </select>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="profession" class="col-sm-2 col-form-label">Pekerjaan *</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="profession" id="profession"
                                value="{{ old('profession') }}" data-parsley-length="[5,255]" required>
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="phone_number" class="col-sm-2 col-form-label">Phone Number</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="text" name="phone_number" id="phone_number"
                                value="{{ old('phone_number', '628') }}" data-parsley-length="[3,255]" >
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="password" class="col-sm-2 col-form-label">Password</label>
                        <div class="col-sm-10">
                            <input class="form-control" type="password" name="password" id="password"
                                data-parsley-length="[6,255]">
                            <p class='help-block'>Please leave empty if use date of birth as a password. Format:
                                DD-MM-YYYY</p>
                        </div>
                    </div>
                    <div class="form-group mb-0">
                        <div>
                            <button type="submit" class="btn btn-primary waves-effect waves-light mr-1">
                                Submit
                            </button>
                            <a class="btn btn-secondary waves-effect waves-light" href="{{ route('admin.data.index') }}"
                                role="button">Cancel</a>
                        </div>
                    </div>
                </form>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@endsection

@section('script')
<!-- Plugins js -->
<script src="{{ URL::asset('assets/libs/parsleyjs/parsleyjs.min.js')}}"></script>

<script src="{{ URL::asset('assets/js/pages/form-validation.init.js')}}"></script>
@endsection

resources/views/admin/user/show.blade.php
@extends('admin.layouts.master')

@section('title', 'Detail Warga: ' . $user->name)

@section('css')
<link href="{{ URL::asset('assets/libs/datatables/datatables.min.css')}}" rel="stylesheet" type="text/css" />
<link href="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.css')}}" rel="stylesheet" type="text/css" />
@endsection

@section('content')

<!-- start page title -->
<div class="row align-items-center">
    <div class="col-sm-6">
        @component('admin.components.breadcumb')
        @slot('title') Detail Warga: {{ $user->name }} @endslot
        @slot('li_1') Warga @endslot
        @endcomponent
    </div>
</div>
<!-- end page title -->

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <table class='table table-bordered'>
                    <tbody>
                        <tr class='active'>
                            <td colspan="2"><strong><i class='fa fa-bars'></i> Detail Warga</strong></td>
                        </tr>
                        <tr>
                            <td width="25%"><strong>Foto</strong></td>
                            <td>
                                <a class="image-popup-no-margins" href="{{ asset($user->photo) }}">
                                    <img class="img-fluid" alt="{{ $user->name }}" src="{{ asset($user->photo) }}"
                                        width="24">
                                </a>
                            </td>
                        </tr>
                        <tr>
                            <td><strong>NIK</strong></td>
                            <td>{{ $user->sin }}</td>
                        </tr>
                        <tr>
                            <td><strong>Nama</strong></td>
                            <td>{{ $user->name }}</td>
                        </tr>
                        <tr>
                            <td><strong>Email</strong></td>
                            <td>{{ $user->email }}</td>
                        </tr>
                        <tr>
                            <td><strong>Tempat, Tanggal Lahir</strong></td>
                            <td>{{ $user->getPsb() }}</td>
                        </tr>
                        <tr>
                            <td><strong>Jenis Kelamin</strong></td>
                            <td>{{ $user->gender }}</td>
                        </tr>
                        <tr>
                            <td><strong>Alamat</strong></td>
                            <td>{{ $user->address ?? '-' }}</td>
                        </tr>
                        <tr>
                            <td><strong>Agama</strong></td>
                            <td>{{ $user->religion }}</td>
                        </tr>
                        <tr>
                            <td><strong>Status Perkawinan</strong></td>
                            <td>{{ $user->marital_status }}</td>
                        </tr>
                        <tr>
                            <td><strong>Pekerjaan</strong></td>
                            <td>{{ $user->profession ?? '-' }}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">

                <h4 class="card-title">Log Activity</h4>
                <table id="datatable" class="table table-bordered dt-responsive nowrap"
                    style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Page</th>
                            <th>Description</th>
                            <th>Method</th>
                            <th>URL</th>
                            <th>IP</th>
                            <th>Agent</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($logs as $log)
                        <tr>
                            <td>{{ $log->created_at->formatLocalized('%d %B %Y %H:%M') }}</td>
                            <td>{{ $log->page }}</td>
                            <td>{{ $log->description }}</td>
                            <td>{{ $log->method }}</td>
                            <td><a href="{{ $log->url }}" title="{{ $log->page }}">{{ $log->url }}</a></td>
                            <td>{{ $log->ip }}</td>
                            <td>{{ $log->agent }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>

            </div>
        </div>
    </div> <!-- end col -->
</div> <!-- end row -->

@endsection

@section('script')

<!-- Plugins js -->
<script src="{{ URL::asset('assets/libs/datatables/datatables.min.js')}}"></script>
<script src="{{ URL::asset('assets/libs/magnific-popup/magnific-popup.min.js')}}"></script>

<script src="{{ URL::asset('assets/js/pages/datatables.init.js')}}"></script>
<script src="{{ URL::asset('assets/js/pages/lightbox.init.js')}}"></script>

@endsection